create table "public"."zoznam_uloh" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "urgent" boolean not null default false,
    "description" text,
    "done" boolean not null default false,
    "done_at" timestamp with time zone,
    "owner" uuid not null
);


alter table "public"."zoznam_uloh" enable row level security;

CREATE UNIQUE INDEX zoznam_uloh_pkey ON public.zoznam_uloh USING btree (id);

alter table "public"."zoznam_uloh" add constraint "zoznam_uloh_pkey" PRIMARY KEY using index "zoznam_uloh_pkey";

alter table "public"."zoznam_uloh" add constraint "zoznam_uloh_owner_fkey" FOREIGN KEY (owner) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."zoznam_uloh" validate constraint "zoznam_uloh_owner_fkey";

grant delete on table "public"."zoznam_uloh" to "anon";

grant insert on table "public"."zoznam_uloh" to "anon";

grant references on table "public"."zoznam_uloh" to "anon";

grant select on table "public"."zoznam_uloh" to "anon";

grant trigger on table "public"."zoznam_uloh" to "anon";

grant truncate on table "public"."zoznam_uloh" to "anon";

grant update on table "public"."zoznam_uloh" to "anon";

grant delete on table "public"."zoznam_uloh" to "authenticated";

grant insert on table "public"."zoznam_uloh" to "authenticated";

grant references on table "public"."zoznam_uloh" to "authenticated";

grant select on table "public"."zoznam_uloh" to "authenticated";

grant trigger on table "public"."zoznam_uloh" to "authenticated";

grant truncate on table "public"."zoznam_uloh" to "authenticated";

grant update on table "public"."zoznam_uloh" to "authenticated";

grant delete on table "public"."zoznam_uloh" to "service_role";

grant insert on table "public"."zoznam_uloh" to "service_role";

grant references on table "public"."zoznam_uloh" to "service_role";

grant select on table "public"."zoznam_uloh" to "service_role";

grant trigger on table "public"."zoznam_uloh" to "service_role";

grant truncate on table "public"."zoznam_uloh" to "service_role";

grant update on table "public"."zoznam_uloh" to "service_role";

create policy "Owner can do everything"
on "public"."zoznam_uloh"
as permissive
for all
to authenticated
using ((auth.is_user_authenticated() AND (owner = auth.uid())));



